require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CalculationsController do

  # This should return the minimal set of attributes required to create a valid
  # Calculation. As you add validations to Calculation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "decision_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CalculationsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all calculations as @calculations" do
      calculation = Calculation.create! valid_attributes
      get :index, {}, valid_session
      assigns(:calculations).should eq([calculation])
    end
  end

  describe "GET show" do
    it "assigns the requested calculation as @calculation" do
      calculation = Calculation.create! valid_attributes
      get :show, {:id => calculation.to_param}, valid_session
      assigns(:calculation).should eq(calculation)
    end
  end

  describe "GET new" do
    it "assigns a new calculation as @calculation" do
      get :new, {}, valid_session
      assigns(:calculation).should be_a_new(Calculation)
    end
  end

  describe "GET edit" do
    it "assigns the requested calculation as @calculation" do
      calculation = Calculation.create! valid_attributes
      get :edit, {:id => calculation.to_param}, valid_session
      assigns(:calculation).should eq(calculation)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Calculation" do
        expect {
          post :create, {:calculation => valid_attributes}, valid_session
        }.to change(Calculation, :count).by(1)
      end

      it "assigns a newly created calculation as @calculation" do
        post :create, {:calculation => valid_attributes}, valid_session
        assigns(:calculation).should be_a(Calculation)
        assigns(:calculation).should be_persisted
      end

      it "redirects to the created calculation" do
        post :create, {:calculation => valid_attributes}, valid_session
        response.should redirect_to(Calculation.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved calculation as @calculation" do
        # Trigger the behavior that occurs when invalid params are submitted
        Calculation.any_instance.stub(:save).and_return(false)
        post :create, {:calculation => { "decision_id" => "invalid value" }}, valid_session
        assigns(:calculation).should be_a_new(Calculation)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Calculation.any_instance.stub(:save).and_return(false)
        post :create, {:calculation => { "decision_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested calculation" do
        calculation = Calculation.create! valid_attributes
        # Assuming there are no other calculations in the database, this
        # specifies that the Calculation created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Calculation.any_instance.should_receive(:update_attributes).with({ "decision_id" => "1" })
        put :update, {:id => calculation.to_param, :calculation => { "decision_id" => "1" }}, valid_session
      end

      it "assigns the requested calculation as @calculation" do
        calculation = Calculation.create! valid_attributes
        put :update, {:id => calculation.to_param, :calculation => valid_attributes}, valid_session
        assigns(:calculation).should eq(calculation)
      end

      it "redirects to the calculation" do
        calculation = Calculation.create! valid_attributes
        put :update, {:id => calculation.to_param, :calculation => valid_attributes}, valid_session
        response.should redirect_to(calculation)
      end
    end

    describe "with invalid params" do
      it "assigns the calculation as @calculation" do
        calculation = Calculation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Calculation.any_instance.stub(:save).and_return(false)
        put :update, {:id => calculation.to_param, :calculation => { "decision_id" => "invalid value" }}, valid_session
        assigns(:calculation).should eq(calculation)
      end

      it "re-renders the 'edit' template" do
        calculation = Calculation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Calculation.any_instance.stub(:save).and_return(false)
        put :update, {:id => calculation.to_param, :calculation => { "decision_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested calculation" do
      calculation = Calculation.create! valid_attributes
      expect {
        delete :destroy, {:id => calculation.to_param}, valid_session
      }.to change(Calculation, :count).by(-1)
    end

    it "redirects to the calculations list" do
      calculation = Calculation.create! valid_attributes
      delete :destroy, {:id => calculation.to_param}, valid_session
      response.should redirect_to(calculations_url)
    end
  end

end
