require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DecisionElementsController do

  # This should return the minimal set of attributes required to create a valid
  # DecisionElement. As you add validations to DecisionElement, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "decision_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DecisionElementsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all decision_elements as @decision_elements" do
      decision_element = DecisionElement.create! valid_attributes
      get :index, {}, valid_session
      assigns(:decision_elements).should eq([decision_element])
    end
  end

  describe "GET show" do
    it "assigns the requested decision_element as @decision_element" do
      decision_element = DecisionElement.create! valid_attributes
      get :show, {:id => decision_element.to_param}, valid_session
      assigns(:decision_element).should eq(decision_element)
    end
  end

  describe "GET new" do
    it "assigns a new decision_element as @decision_element" do
      get :new, {}, valid_session
      assigns(:decision_element).should be_a_new(DecisionElement)
    end
  end

  describe "GET edit" do
    it "assigns the requested decision_element as @decision_element" do
      decision_element = DecisionElement.create! valid_attributes
      get :edit, {:id => decision_element.to_param}, valid_session
      assigns(:decision_element).should eq(decision_element)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DecisionElement" do
        expect {
          post :create, {:decision_element => valid_attributes}, valid_session
        }.to change(DecisionElement, :count).by(1)
      end

      it "assigns a newly created decision_element as @decision_element" do
        post :create, {:decision_element => valid_attributes}, valid_session
        assigns(:decision_element).should be_a(DecisionElement)
        assigns(:decision_element).should be_persisted
      end

      it "redirects to the created decision_element" do
        post :create, {:decision_element => valid_attributes}, valid_session
        response.should redirect_to(DecisionElement.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved decision_element as @decision_element" do
        # Trigger the behavior that occurs when invalid params are submitted
        DecisionElement.any_instance.stub(:save).and_return(false)
        post :create, {:decision_element => { "decision_id" => "invalid value" }}, valid_session
        assigns(:decision_element).should be_a_new(DecisionElement)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DecisionElement.any_instance.stub(:save).and_return(false)
        post :create, {:decision_element => { "decision_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested decision_element" do
        decision_element = DecisionElement.create! valid_attributes
        # Assuming there are no other decision_elements in the database, this
        # specifies that the DecisionElement created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DecisionElement.any_instance.should_receive(:update_attributes).with({ "decision_id" => "1" })
        put :update, {:id => decision_element.to_param, :decision_element => { "decision_id" => "1" }}, valid_session
      end

      it "assigns the requested decision_element as @decision_element" do
        decision_element = DecisionElement.create! valid_attributes
        put :update, {:id => decision_element.to_param, :decision_element => valid_attributes}, valid_session
        assigns(:decision_element).should eq(decision_element)
      end

      it "redirects to the decision_element" do
        decision_element = DecisionElement.create! valid_attributes
        put :update, {:id => decision_element.to_param, :decision_element => valid_attributes}, valid_session
        response.should redirect_to(decision_element)
      end
    end

    describe "with invalid params" do
      it "assigns the decision_element as @decision_element" do
        decision_element = DecisionElement.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DecisionElement.any_instance.stub(:save).and_return(false)
        put :update, {:id => decision_element.to_param, :decision_element => { "decision_id" => "invalid value" }}, valid_session
        assigns(:decision_element).should eq(decision_element)
      end

      it "re-renders the 'edit' template" do
        decision_element = DecisionElement.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DecisionElement.any_instance.stub(:save).and_return(false)
        put :update, {:id => decision_element.to_param, :decision_element => { "decision_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested decision_element" do
      decision_element = DecisionElement.create! valid_attributes
      expect {
        delete :destroy, {:id => decision_element.to_param}, valid_session
      }.to change(DecisionElement, :count).by(-1)
    end

    it "redirects to the decision_elements list" do
      decision_element = DecisionElement.create! valid_attributes
      delete :destroy, {:id => decision_element.to_param}, valid_session
      response.should redirect_to(decision_elements_url)
    end
  end

end
